name: README

on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install -r waka/requirements.txt
      - name: Collect Wakatime and Update Readme
        env:
          INPUT_WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          INPUT_GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          INPUT_COMMIT_USERNAME: "ngocnhan2003"
          INPUT_COMMIT_EMAIL: "ngocnhan.nplus@gmail.com"
        run: |
          python waka/main.py
