name: BUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: "preview"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ENV
        run: |
          sudo apt-get install minify
      - name: Start minify
        run: |
          cat minify.txt | while read line 
          do
            minify $line -o $line
          done
          date >> last_build.log
      - name: Git job
        run: |
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "ngocnhan2003"
          git branch -l $BRANCH | grep $BRANCH && git branch -d $BRANCH
          git checkout -b $BRANCH
      - name: Rollup version and push
        run: |
          CC=$(git rev-list init..master --count)
          let "CC++"
          VERSION="v0.$CC"
          python versioning.py $VERSION
          git add . 
          git commit -m "deploy for $BRANCH @ $(date)"
          git push -f origin $BRANCH
          git tag $VERSION
          git push origin $VERSION

      - name: Craw Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ngocnhan2003/ngocnhan2003
          event-type: trigger_refresh
