name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: "preview"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ENV
        run: |
          sudo apt-get install minify
      - name: Start minify
        run: |
          cat minify.txt | while read line 
          do
            minify $line -o $line
          done
      - name: Git job
        run: |
          git config --global user.email "deploy@ngocnhan2003.github.io"
          git config --global user.name "DEPLOY BOT"
          git branch -l $BRANCH | grep $BRANCH && git branch -d $BRANCH
          git checkout -b $BRANCH
          git add . 
          git commit -m "deploy for $BRANCH @ $(date)"
          git tag "CRAW"
          git push -f origin $BRANCH

