name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: "preview"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ENV
        run: |
          sudo apt-get install minify
      - name: Start minify
        run: |
          cat minify.txt | while read line 
          do
            minify $line -o $line
          done
          date >> last_deploy.log
      - name: Git job
        run: |
          git config --global user.email "deploy@ngocnhan2003.github.io"
          git config --global user.name "DEPLOY BOT"
          git branch -l $BRANCH | grep $BRANCH && git branch -d $BRANCH
          git checkout -b $BRANCH
      - name: Rollup version and push
        run: |
          CC=$(git rev-list b22c84b..master --count)
          let "CC++"
          VERSION="v0.$CC"
          python version_handler.py $VERSION
          git add . 
          git commit -m "deploy for $BRANCH @ $(date)"
          git push -f origin $BRANCH
          git tag $VERSION
          git push origin $VERSION

      - name: Craw Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ngocnhan2003/ngocnhan2003.github.io
          event-type: Start instacraw
