name: CRAW

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: ["trigger_craw"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: "preview"
      INSTACRAWJSON: "assets/files/instacraw.json"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ENV
        run: |
          pip install requests
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "ngocnhan2003"
          git checkout $BRANCH
          git pull
      - name: Craw insta
        run: |
          python crawling.py $INSTACRAWJSON
      - name: Git job
        run: |
          if [ -n "$(git status -s $INSTACRAWJSON)" ]; then
            git add $INSTACRAWJSON
            git add assets/images
            git commit -m "craw update for $BRANCH @ $(date)"
            git push -f origin $BRANCH
            echo "Pushed update"
          else
            echo "Nothing to update"
          fi
      - name: Refresh CDN Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ngocnhan2003/profile
          event-type: trigger_refresh_cdn
