name: REFRESH

on:
  repository_dispatch:
    types: ['trigger_refresh_cdn']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: preview
      - name: Setup ENV
        run: |
          pip install requests
      - name: Refresh CDN
        run: |
          python refreshing.py
