name: REFRESH

on:
  schedule:
    - cron:  "0 */4 * * *"
  repository_dispatch:
    types: ['trigger_refresh_cdn']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: "preview"
      INSTACRAWJSON: "assets/files/instacraw.json"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: $BRANCH
      - name: Setup ENV
        run: |
          pip install requests
      - name: Refresh CDN
        run: |
          python refreshing.py
