# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup ENV
        run: |
          sudo apt-get install minify

      - name: Start minify
        run: |
          cat minify.txt | while read line 
          do
            minify $line > $line
          done

      - name: Git job
        run: |
          git config --global user.email "deploy@ngocnhan2003.github.io"
          git config --global user.name "DEPLOY BOT"
          export BRANCH=preview
          git branch -l $BRANCH | grep $BRANCH && git branch -d $BRANCH && git push origin --delete $BRANCH
          git checkout -b $BRANCH
          git add . 
          git commit -m "deploy for $BRANCH @ $(date)"
          git push origin $BRANCH

