# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Start minify
          git status
          sudo apt-get install minify
          minify assets/js/main.js > assets/js/main.js
          minify assets/css/main.css > assets/js/main.js
          minify index.html > index.html
          ls -l  assets/js
          git branch -d preview
          git checkout -b preview
          git add . 
          git commmit -m "deploy for preview"
          git push origin preview

